name: Service Container

on: 
    push:
    workflow_dispatch:
        

jobs:
    service_container:
        runs-on: ubuntu-latest

        name: Unit Testing Service
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        
        env:
          MONGO_URI: 'mongodb://localhost:27017/superData'
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password


        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Node Installation
              uses: actions/setup-node@v6

            - name: Install Dependencies
              run: |
                npm install

            - name: Unit Testing
              run: |
                npm test
                ls -lrth

            - name: Upload Artifactory
              uses: actions/upload-artifact@v4
              with:
                name: Node_Modules
                path: node_modules


